### ISSUE TITLE
Update README.md to Standard format

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/Rock-Papers-Scissors-Game#1]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Check out this [link](https://github.com/salman-bhai/E-Manager/blob/master/README.md) to understand better.

**Comment by mithun-daa** [comment]
What does this mean? What standard format are you talking about?

**Comment by sbshah97** [comment]
Click on the link in the description, @mithun-daa

**Comment by luongthomas** [comment]
Claim

**Comment by luongthomas** [comment]
I made a pull request #10 

I also linked to a License, which should be added afterwards.  

Let me know what you think of the new Readme.md

**Comment by sbshah97** [comment]
Well done @luongthomas
