### ISSUE TITLE
Create CONTRIBUTING.md file

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/Rock-Papers-Scissors-Game#2]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Check out this [link](https://github.com/salman-bhai/E-Manager) to understand better.

**Comment by aditya5558** [comment]
claimed
