### ISSUE TITLE
Create Version 2.0 of the game

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/Rock-Papers-Scissors-Game#4]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Create a new file called `rps2.js` and push your code in it.

**Comment by luongthomas** [comment]
Hello, I'm interested in helping but I'm unsure what version 2.0 would be like.

If we can clarify this, I would love to claim the task.

**Comment by sbshah97** [comment]
Read the README for details. Let me know if you need help.

**Comment by luongthomas** [comment]
Created a pull request #8 

Added ability to display score, ability to play five rounds, and fixed the random number generation.  Before, scissors wasn't able to be randomly chosen by the computer.

This is for version 2.0.

Please let me know what you think of it.

edit: I re-read the rules and saw I had to claim the issue before posting a pull request.  I don't see an option to claim this issue.  Apologies in advance.

**Comment by sbshah97** [comment]
Hey, @luongthomas you just need to type in `Claim` to claim the Issue. 

Also check the description again. I forgot to mention to make a **separate file** for version 2.0

**Comment by luongthomas** [comment]
Claim

**Comment by luongthomas** [comment]
Created Pull request #9 

Added ability to play 5 rounds, fixed random number generation since paper wasn't being picked as a computerChoice, and can display the user's end score after all five rounds.

Added it as a new file called rps2.js
